// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzIHBUa_6qtlUqpbHbhmPxBZrntauQ6dw',
    appId: '1:1098709745631:web:7a19af25f0356419f48e6a',
    messagingSenderId: '1098709745631',
    projectId: 'boxstock-c4c33',
    authDomain: 'boxstock-c4c33.firebaseapp.com',
    storageBucket: 'boxstock-c4c33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAueBg4cGr2CAvlQvahxF7loTjrOSfKrRg',
    appId: '1:1098709745631:android:7f6d67693a0413acf48e6a',
    messagingSenderId: '1098709745631',
    projectId: 'boxstock-c4c33',
    storageBucket: 'boxstock-c4c33.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIbG1Ogr0NXAAfL3GlDS3nHSxeG6yIJPE',
    appId: '1:1098709745631:ios:c198941ab82051a2f48e6a',
    messagingSenderId: '1098709745631',
    projectId: 'boxstock-c4c33',
    storageBucket: 'boxstock-c4c33.firebasestorage.app',
    iosBundleId: 'com.example.boxstock',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIbG1Ogr0NXAAfL3GlDS3nHSxeG6yIJPE',
    appId: '1:1098709745631:ios:c198941ab82051a2f48e6a',
    messagingSenderId: '1098709745631',
    projectId: 'boxstock-c4c33',
    storageBucket: 'boxstock-c4c33.firebasestorage.app',
    iosBundleId: 'com.example.boxstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzIHBUa_6qtlUqpbHbhmPxBZrntauQ6dw',
    appId: '1:1098709745631:web:72083db0fec5319bf48e6a',
    messagingSenderId: '1098709745631',
    projectId: 'boxstock-c4c33',
    authDomain: 'boxstock-c4c33.firebaseapp.com',
    storageBucket: 'boxstock-c4c33.firebasestorage.app',
  );
}
